apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-program
  name: resources-service
  labels:
    app: resources-service
    type: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resources-service
      type: app
  template:
    metadata:
      labels:
        app: resources-service
        type: app
    spec:
      containers:
        - name: resources-service
          image: resource-image:latest
          imagePullPolicy: Never
          env:
            - name: SONGS_MS_URL
              value: "app.songs-service"
            - name: SONGS_MS_PORT
              value: "8080"
            - name: RESOURCES_MS_NAME
              value: "resources-service"
            - name: RESOURCES_MS_PORT
              value: "8080"
            - name: RESOURCES_DB_URL
              value: "resources-service-db-service"
            - name: RESOURCES_DB_PORT
              value: "5433"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
