apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: k8s-program
  name: songs-service-db
  labels:
    app: songs-service
    type: db
    db: postgresql

spec:
  replicas: 1
  revisionHistoryLimit: 10
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: songs-service
      type: db
      db: postgresql
  template:
    metadata:
      labels:
        app: songs-service
        type: db
        db: postgresql
    spec:
      containers:
        - name: songs-services-db
          image: postgres:13
          envFrom:
            - configMapRef:
                name: db-config
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: ss-db-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 1
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
      volumes:
        - name: ss-db-storage
          hostPath:
            path: /ss-db-data
            type: DirectoryOrCreate
