apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songs-service-pvc
  namespace: k8s-program
  labels:
    app: songs-service
    type: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: songs-service-pv